model:
  learning_task: LINK_PREDICTION
  embeddings:
    dimension: 50
    init:
      type: NORMAL
      options:
        mean: 0
        std: 0.001
  encoder:
    use_hashmap_sets: false
    use_incoming_nbrs: true
    use_outgoing_nbrs: true
    layers:
      - train_neighbor_sampling:
          type: ALL
        eval_neighbor_sampling:
          type: ALL
        init:
          type: GLOROT_NORMAL
        type: GRAPH_SAGE
        options:
          input_dim: 50
          output_dim: 50
          aggregator: MEAN
        bias: true
        bias_init:
          type: ZEROS
        activation: NONE
    optimizer:
      type: ADAGRAD
      options:
        learning_rate: 0.1
  decoder:
    type: DISTMULT
    options:
      input_dim: 50
      inverse_edges: true
    optimizer:
      type: ADAGRAD
      options:
        learning_rate: 0.1
  loss:
    type: SOFTMAX
    options:
      reduction: SUM
storage:
  device_type: cpu
  dataset:
    base_directory: datasets/fb15k237/
    num_edges: 272115
    num_train: 272115
    num_nodes: 14541
    num_relations: 237
    num_valid: 17535
    num_test: 20466
  edges:
    type: FLAT_FILE
  embeddings:
    type: PARTITION_BUFFER
    options:
      num_partitions: 32
      buffer_capacity: 8
      prefetching: true
      fine_to_coarse_ratio: 4
      num_cache_partitions: 0
      edge_bucket_ordering: TWO_LEVEL_BETA
      randomly_assign_edge_buckets: true
  prefetch: true
  shuffle_input: true
  full_graph_evaluation: true
training:
  batch_size: 1000
  negative_sampling:
    num_chunks: 10
    negatives_per_positive: 500
    degree_fraction: 0.0
    filtered: false
  num_epochs: 10
  pipeline:
    sync: true
  epochs_per_shuffle: 1
  logs_per_epoch: 10
evaluation:
  batch_size: 10000
  negative_sampling:
    filtered: true
  pipeline:
    sync: true
  epochs_per_eval: 1